language: node_js
install: npm i
node_js:
  - '11'
script:
- npm run test

deploy:
  provider: npm
  email: kohllisti@riseup.net
  api_key:
    secure: efwtth1jAb6XAzHYnmryDPtmP49/IfBIDVycETKIzmUuErC8ArNwPry+1Z1L4ckingbkifBP1bk5VVMlE64n17ygmALB894HQCMFwq7PT0n/MTQkxcm3rcVAyrtcko3d1IfEhw2ae0xGhi6vqiDwOWECHFWaMI+2KRl+Y5pTA/wVSAx8ifSeJTO58N8/7fME7mytAd+GPNoepmF/QFDVB73unGG9W5JPD8VImRh8+xW2+PzNcoFBM9bZf2AjD+60GxKpjWMWANv8KuqMx3r9GJ1FnK96gtVbzIcRmpZ33EYFE6FuPLRphi+yboAQPlcjsTs06J662auRb0MZjIYYyZjvgWv072q6nQScXrSI2JcU5G4H9oCpuVW2QGD5DhEQwIlfxv6cBDzhF0oc9NCNM8YETH7iwtbSDOJii+TjWvHuWOVnbOq0/sfDr+ABtR6+Nqgr3gWUFVM2dgbkX+HjbERKe1BzgWF9e9phnhUteiXscKGos3K25/tRegU/xKnYDhko4LuTRAymcMljofBSIm6sdXcN5MXLFb+g7Ar/ibk5Q/pGSsrd9scOwgovb2wUweITFw1U3zvFeh1SIXQcPU2LbxEKHZzhn63goyfAs/VsyAP0XxOimJZaeLHwuCCTC0+aDNtd8AuvKlzQS0bFxd01Xx+lmQDfsDhBvPl6NcM=
  on:
    tags: true
    repo: aktionskarten/AktionskartenMarker
    branch: gh-pages
