name: lint and publish

on:
  push:
    tags:
      - '**'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo and subrepos
        uses: actions/checkout@v2
      - 
        name: Install npm packages
        run : npm install --only=dev
      - 
        name: Run eslint 
        run: npm run lint 
      - 
        name: Publish to npmjs.com
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
